path:
  /api/products:
    get:
      sumary: Trea todos los productos de la base de datos
      tags: 
        - Products
      responses:
        "200": 
          description: Muestra todos los productos traidos de la base de datos configurado con un paginate
        "500":
          description: Error interno
    post:
      sumary: Agrega un nuevo producto a la base de datos, Esta ruta solo tienen accesso los usuarios con role admin
      tags:
        - Products
      responses:
        "200": 
          description: Devuelve un mensaje de New product created y muestra el nuevo producto creado
        "400":
          description: Devuelve un mensaje de some required data is missing  
  /api/products/:pid:
    get:
      sumary: Ubica un producto especifico en la base de datos filtrando por id
      tags:
        - products
      responses:
        "200": 
          description: Devuelve un mensaje de this product is y el objeto del producto encontrado
        "400":
          description: Devuelve un mensaje de Product not found                 
    put:
      sumary: Modifica un producto ya existente en la base de datos, a esta ruta solo tienen acceso los usuarios con el rol de admin
      tags:
        - Products
      responses:
        "200":
          description: Este status devuelve un mensaje de Product updated successfully con un objeto del producto modificado
        "400":
          description: Este status devuelve un mensaje de Product not found    
    delete:
      sumary: Elimina un producto ya existente en la base de datos, a esta ruta solo tienen acceso los usuarios con el rol de admin
      tags:
        - Products
      responses:
        "200":
          description: Este estatus devuelve un mensaje de Product deleted successfully
        "400":
          description: Este status devuelve un mensaje de  Product not found 
